### ISSUE TITLE
Rewrite scripts in JavaScript

### ISSUE THREAD

**Issue by dlongley** [digitalbazaar/bedrock-dev#1]
I recommend that the scripts in this repo be rewritten in JavaScript and be based on a JavaScript tool chain. That will lower the barrier for people who would like to contribute and also encourage contributions to improve the dev environment.

**Comment by msporny** [comment]
I didn't know how complex the scripting would get, and I always feel like I have huge padded gloves on when trying to do similar things to a bash script in Javascript, so I implemented the first version in bash since it's easier to hack on stuff like this than Javascript.

I'm also not entirely convinced that Javascript is good for tasks that require arbitrary unix utilities to be composed together. The scripts are pretty simple and will probably not need too much more complexity added to them. I've setup both npm and bower installs to just read from the package.json and bower.json files and do its thing from there.

Now that we have /something/ that works, we could move to Javascript. The move would make me less likely to contribute more than minor changes. I'm not saying I wouldn't, I'm just saying that it's not my preferred way to script systems.

That said, there is Windows. So, a port to Javascript may be inescapable.

**Comment by dlongley** [comment]
Closing, this won't be happening.
